/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PdfDocumentService } from "../pdfDocument.service";
import { PdfDocumentCreateInput } from "./PdfDocumentCreateInput";
import { PdfDocument } from "./PdfDocument";
import { PdfDocumentFindManyArgs } from "./PdfDocumentFindManyArgs";
import { PdfDocumentWhereUniqueInput } from "./PdfDocumentWhereUniqueInput";
import { PdfDocumentUpdateInput } from "./PdfDocumentUpdateInput";
import { SectionFindManyArgs } from "../../section/base/SectionFindManyArgs";
import { Section } from "../../section/base/Section";
import { SectionWhereUniqueInput } from "../../section/base/SectionWhereUniqueInput";

export class PdfDocumentControllerBase {
  constructor(protected readonly service: PdfDocumentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PdfDocument })
  async createPdfDocument(
    @common.Body() data: PdfDocumentCreateInput
  ): Promise<PdfDocument> {
    return await this.service.createPdfDocument({
      data: data,
      select: {
        createdAt: true,
        filePath: true,
        id: true,
        updatedAt: true,
        uploadedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PdfDocument] })
  @ApiNestedQuery(PdfDocumentFindManyArgs)
  async pdfDocuments(@common.Req() request: Request): Promise<PdfDocument[]> {
    const args = plainToClass(PdfDocumentFindManyArgs, request.query);
    return this.service.pdfDocuments({
      ...args,
      select: {
        createdAt: true,
        filePath: true,
        id: true,
        updatedAt: true,
        uploadedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PdfDocument })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async pdfDocument(
    @common.Param() params: PdfDocumentWhereUniqueInput
  ): Promise<PdfDocument | null> {
    const result = await this.service.pdfDocument({
      where: params,
      select: {
        createdAt: true,
        filePath: true,
        id: true,
        updatedAt: true,
        uploadedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PdfDocument })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePdfDocument(
    @common.Param() params: PdfDocumentWhereUniqueInput,
    @common.Body() data: PdfDocumentUpdateInput
  ): Promise<PdfDocument | null> {
    try {
      return await this.service.updatePdfDocument({
        where: params,
        data: data,
        select: {
          createdAt: true,
          filePath: true,
          id: true,
          updatedAt: true,
          uploadedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PdfDocument })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePdfDocument(
    @common.Param() params: PdfDocumentWhereUniqueInput
  ): Promise<PdfDocument | null> {
    try {
      return await this.service.deletePdfDocument({
        where: params,
        select: {
          createdAt: true,
          filePath: true,
          id: true,
          updatedAt: true,
          uploadedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/sections")
  @ApiNestedQuery(SectionFindManyArgs)
  async findSections(
    @common.Req() request: Request,
    @common.Param() params: PdfDocumentWhereUniqueInput
  ): Promise<Section[]> {
    const query = plainToClass(SectionFindManyArgs, request.query);
    const results = await this.service.findSections(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,
        id: true,

        pdfDocument: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/sections")
  async connectSections(
    @common.Param() params: PdfDocumentWhereUniqueInput,
    @common.Body() body: SectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sections: {
        connect: body,
      },
    };
    await this.service.updatePdfDocument({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/sections")
  async updateSections(
    @common.Param() params: PdfDocumentWhereUniqueInput,
    @common.Body() body: SectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sections: {
        set: body,
      },
    };
    await this.service.updatePdfDocument({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/sections")
  async disconnectSections(
    @common.Param() params: PdfDocumentWhereUniqueInput,
    @common.Body() body: SectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sections: {
        disconnect: body,
      },
    };
    await this.service.updatePdfDocument({
      where: params,
      data,
      select: { id: true },
    });
  }
}
